services:
  backend:
    image: "${IMAGE_PREFIX-}backend:${IMAGE_TAG}"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      DJANGO_DEBUG: 'true'
      PRODUCTION: 'true'
      ROOT_URL: 'http://localhost'
      ROOT_HOST: 't1m.me'
      EXTRA_TRUSTED_ORIGINS: ''
      DJANGO_SECRET_KEY: 'SomeSecret'
      DJANGO_ALLOWED_HOSTS: '*'
      REDIS_URL: 'redis://redis:6379'
      USE_NEXTJS_PROXY_ROUTES: 'true'
      NEXTJS_HOST_URL: 'http://frontend:3000'
      BASE_ADMIN_USERNAME: 'admin'
      BASE_ADMIN_USER_PASSWORD: 'password'
  frontend:
    image: "${IMAGE_PREFIX-}frontend:${IMAGE_TAG}"
    build:
      context: ./frontend
      dockerfile: ./prod.dockerfile
    environment:
      PUBLIC_ENV__BUILD_TYPE: 'web'
      PUBLIC_ENV__GUEST_LOGIN_ALLOWED: 'true'
      PUBLIC_ENV__GUEST_USERNAME: 'test+msgmate9@msgmate.io'
      PUBLIC_ENV__GUEST_PASSWORD: 'Test123!'
      PUBLIC_ENV__FRONTNED_BACKEND_ROUTE: 'http://localhost'
      PUBLIC_ENV__ROUTE_PREFIX: ''
      PUBLIC_ENV__WEBSOCKET_PROTOCOLL: 'ws://'
      PUBLIC_ENV__WEBSOCKET_HOST: 'localhost'
      PUBLIC_ENV__WEBSOCKET_PATH: '/api/core/ws'
      INTERNAL_BACKEND_ROUTE: 'http://backend:8000'
    ports:
      - "3000:3000"
      - "24678:24678"
  redis:
    image: redis:5
  ingress:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
