services:
  backend:
    image: "${IMAGE_PREFIX-}backend:${IMAGE_TAG}"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      DJANGO_DEBUG: 'true'
      PRODUCTION: 'true'
      ROOT_URL: 'http://localhost'
      ROOT_HOST: 't1m.me'
      EXTRA_TRUSTED_ORIGINS: ''
      DJANGO_SECRET_KEY: 'SomeSecret'
      DJANGO_ALLOWED_HOSTS: '*'
      REDIS_URL: 'redis://redis:6379'
      USE_NEXTJS_PROXY_ROUTES: 'true'
      NEXTJS_HOST_URL: 'http://frontend:3000'
      BASE_ADMIN_USERNAME: 'admin'
      BASE_ADMIN_USER_PASSWORD: 'password'
  frontend:
    image: "${IMAGE_PREFIX-}frontend:${IMAGE_TAG}"
    build:
      context: ./frontend
      dockerfile: ./prod.dockerfile
    environment:
      PUBLIC_ENV__ROUTE_PREFIX: ''
    ports:
      - "3000:3000"
      - "24678:24678"
  hal:
    image: "${IMAGE_PREFIX-}hal:${IMAGE_TAG}"
    build:
      context: ./hal
      dockerfile: ./Dockerfile
    environment:
      DJANGO_DEBUG: 'true'
      PRODUCTION: 'true'
      ROOT_URL: 'http://localhost'
      ROOT_HOST: 't1m.me'
      EXTRA_TRUSTED_ORIGINS: 'http://localhost:8000'
      DJANGO_SECRET_KEY: 'SomeSecret'
      DJANGO_ALLOWED_HOSTS: '*'
      REDIS_URL: 'redis://redis-hal:6379'
      EXTRA_APPS: ${EXTRA_APPS-}
      BASE_ADMIN_USERNAME: 'admin'
      BASE_ADMIN_USER_PASSWORD: 'password'
      HAL_PASSWORD: "Test123!"
      GROQ_API_KEY: ${GROQ_API_KEY-}
      DEEPINFRA_API_KEY: ${DEEPINFRA_API_KEY-}
      OPENAI_API_KEY: ${OPENAI_API_KEY-}
  redis:
    image: redis:5
  ingress:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
