services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "backend"
    environment:
      DJANGO_DEBUG: 'true'
      PRODUCTION: 'true'
      ROOT_URL: 'http://localhost'
      ROOT_HOST: 't1m.me'
      EXTRA_TRUSTED_ORIGINS: 'http://localhost:8000'
      DJANGO_SECRET_KEY: 'SomeSecret'
      DJANGO_ALLOWED_HOSTS: '*'
      REDIS_URL: 'redis://redis:6379'
      BASE_ADMIN_USERNAME: 'admin'
      BASE_ADMIN_USER_PASSWORD: 'password'
      CREATE_TEST_USERS: 'true'
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
  hal:
    image: "hal"
    build:
      context: ./hal
      dockerfile: ./Dockerfile
    environment:
      DJANGO_DEBUG: 'true'
      PRODUCTION: 'true'
      ROOT_URL: 'http://localhost'
      ROOT_HOST: 't1m.me'
      EXTRA_TRUSTED_ORIGINS: 'http://localhost:8000'
      DJANGO_SECRET_KEY: 'SomeSecret'
      DJANGO_ALLOWED_HOSTS: '*'
      REDIS_URL: 'redis://redis-hal:6379'
      EXTRA_APPS: ${EXTRA_APPS-}
      BASE_ADMIN_USERNAME: 'admin'
      BASE_ADMIN_USER_PASSWORD: 'password'
      HAL_PASSWORD: "Test123!"
      GROQ_API_KEY: ${GROQ_API_KEY-}
      DEEPINFRA_API_KEY: ${DEEPINFRA_API_KEY-}
      OPENAI_API_KEY: ${OPENAI_API_KEY-}
    ports:
      - "8001:8000"
      - "5555:5555"
    volumes:
      - ./hal:/hal
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "frontend"
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./frontend/:/frontend/
    command: sh -c "npm install && npm run dev"
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  redis-hal:
    image: redis:5
    ports:
      - "6380:6379"
  ingress:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
