# Generated by Django 4.1.2 on 2024-01-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
    ]
