# Generated by Django 4.1.2 on 2024-04-17 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatsettings_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsettings',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='chat.chat'),
        ),
    ]
