# Generated by Django 4.1.2 on 2024-05-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chatsettings_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconnections',
            name='connection_counter',
            field=models.IntegerField(default=0),
        ),
    ]
