# Generated by Django 4.1.2 on 2024-06-01 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatconnections_connection_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hide_message', models.BooleanField(default=False)),
                ('data_type', models.CharField(choices=[('custom', 'Custom'), ('audio_b64', 'Audio B64')], default='custom', max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_message_message', to='chat.message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='data_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_data_message', to='chat.datamessage'),
        ),
    ]
