# Generated by Django 4.1.2 on 2024-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_datamessage_message_data_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamessage',
            name='data_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('audio_b64', 'Audio B64'), ('signal', 'Signal')], default='custom', max_length=255),
        ),
    ]
