# Generated by Django 4.1.2 on 2024-06-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_datamessage_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamessage',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_message_message', to='chat.message'),
        ),
    ]
