{{- if .Values.backend.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  namespace: {{ .Values.rootNamespace }}
  labels:
    app: {{ .Values.backend.deploymentName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  selector:
    app: {{ .Values.backend.deploymentName }}
{{- end}}