{{- if .Values.backend.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: {{ .Values.rootNamespace }}
type: Opaque
data:
{{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}