---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: fontend
  template:
    metadata:
      labels:
        app: fontend
    spec:
      containers:
        - name: fontend
          image: {{ .Values.fontend.imageURL }}
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: fontend-secret
      {{- if .Values.fontend.registry.authRequired }}
      imagePullSecrets:
        - name: {{ .Values.fontend.registry.secretName }}
      {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fontend-secrets
  namespace: {{ .Values.rootNamespace }}
type: Opaque
data:
{{- range $key, $value := .Values.fontend.env }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}