{{- if .Values.hal.use }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hal-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: hal-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hal-redis
  template:
    metadata:
      labels:
        app: hal-redis
    spec:
      containers:
        - name: hal-redis
          image: redis:5
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: hal-redis-service
  namespace: {{ .Values.namespace }}
  labels:
    app: hal-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: hal-redis
{{- end }}