{{- if .Values.registry.use }}
{{- range .Values.registry.registrySecrets }}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Values.rootNamespace }}
stringData:
  .dockerconfigjson: >
    {{
      (
        dict "auths"
        (
          dict .host
          (
            dict "auth" .token
          )
        )
      )
      |
      toJson
    }}
{{- end }}
{{- end }}