# Generated by Django 5.0.3 on 2024-06-23 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('task_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('text_chat', 'Text Chat'), ('audio_chat', 'Audio Chat')], default='text_chat', max_length=255)),
            ],
        ),
    ]
