# Generated by Django 4.1.2 on 2024-03-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_consumerconnections_connections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_secret',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
