# Generated by Django 4.1.2 on 2024-04-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reveal_secret',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
