---
namespace: tims-stack-dev
registry:
  use: false
  authToken: "token"
certmanager:
  use: false
  name: letsencrypt-prod
redis:
  use: true
  port: 6379
  serviceName: redis-db-svc
ingress:
  use: true
backend:
  replicas: 1
  imageURL: localhost:32000/backend-image:latest
  registry:
    authRequired: false
    secretName: dockerconfigjson-github-com
  env:
    DJANGO_DEBUG: "true"
    PRODUCTION: "true"
    ROOT_URL: "http://localhost"
    ROOT_HOST: "t1m.me"
    EXTRA_TRUSTED_ORIGINS: ""
    DJANGO_SECRET_KEY: "SomeSecret"
    DJANGO_ALLOWED_HOSTS: "*"
    REDIS_URL: "redis://redis-db-svc.tims-stack-dev.svc.cluster.local:6379"
    USE_NEXTJS_PROXY_ROUTES: "true"
    NEXTJS_HOST_URL: "http://frontend-service.tims-stack-dev.svc.cluster.local:3000"
    BASE_ADMIN_USERNAME: "admin"
    BASE_ADMIN_USER_PASSWORD: "password"
frontend:
  imageURL: localhost:32000/frontend-image:latest
  registry:
    authRequired: false
    secretName: dockerconfigjson-github-com
  env:
    INTERNAL_BACKEND_ROUTE: "http://backend-service.tims-stack-dev.svc.cluster.local:8000"
    FRONTNED_BACKEND_ROUTE: ""
    WEBSOCKET_PROTOCOLL: "ws://"
