namespace: default
registry:
  use: false
  host: "ghcr.io"
  authToken: "token"
certmanager:
  use: false
  name: letsencrypt-prod
redis:
  use: true
  port: 6379
  serviceName: redis-db-svc
ingress:
  use: true
  host: localhost
backend:
  replicas: 1
  imageURL: localhost:32000/open-chat-backend:latest
  registry:
    authRequired: false
    secretName: dockerconfigjson-github-com
  env:
    DJANGO_DEBUG: "true"
    PRODUCTION: "true"
    ROOT_URL: "http://localhost"
    ROOT_HOST: "localhost"
    EXTRA_TRUSTED_ORIGINS: ""
    DJANGO_SECRET_KEY: "SomeSecret"
    DJANGO_ALLOWED_HOSTS: "*"
    REDIS_URL: "redis://redis-service.default.svc.cluster.local:6379"
    USE_NEXTJS_PROXY_ROUTES: "true"
    NEXTJS_HOST_URL: "http://frontend-service.default.svc.cluster.local:3000"
    BASE_ADMIN_USERNAME: "admin"
    BASE_ADMIN_USER_PASSWORD: "password"
frontend:
  replicas: 1
  imageURL: localhost:32000/open-chat-frontend:latest
  registry:
    authRequired: false
    secretName: dockerconfigjson-github-com
  env:
    INTERNAL_BACKEND_ROUTE: "http://backend-service.default.svc.cluster.local:8000"
    PUBLIC_ENV__GUEST_LOGIN_ALLOWED: "true"
    PUBLIC_ENV__GUEST_USERNAME: "testUser1"
    PUBLIC_ENV__GUEST_PASSWORD: "Test123!"
    PUBLIC_ENV__FRONTNED_BACKEND_ROUTE: "http://localhost"
    PUBLIC_ENV__WEBSOCKET_PROTOCOLL: "ws://"
    PUBLIC_ENV__WEBSOCKET_HOST: "localhost"
    PUBLIC_ENV__WEBSOCKET_PATH: "/api/core/ws"
    PUBLIC_ENV__STATIC_EXPORT: "false"
    PUBLIC_ENV__ROUTE_PREFIX: ""
postgresql:
  use: false
  auth:
    username: "admin"
    password: "password"
    database: "openchat"
mixtral:
  use: false