# Generated by Django 4.1.2 on 2023-07-02 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_changehistory_userprofile_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='changehistory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_history_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
