# Generated by Django 4.1.2 on 2024-01-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='automated',
            field=models.BooleanField(default=False),
        ),
    ]
