# Generated by Django 4.1.2 on 2024-03-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_message_chat_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerconnections',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='consumerconnections',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Connections',
        ),
        migrations.DeleteModel(
            name='ConsumerConnections',
        ),
    ]
