# Generated by Django 4.1.2 on 2024-03-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default="Hello there I'm using open-chat!"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description_title',
            field=models.TextField(default='About Me:'),
        ),
    ]
